QtumSignService:
    Db:
        LogsConnString:
            settings-key: "QtumSignService-LogsConnString"
            types:
                - AzureBlobStorage
                - Tag
Network:
    settings-key: "QtumSignService-Network"
    
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl 

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName